name: serva
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: 3.0.1

dependencies:
  animated_splash_screen: ^1.3.0
  bloc: ^8.1.0
  carousel_slider: ^4.1.1
  
  cloud_firestore: ^3.5.1
  firebase_auth: ^3.11.2
  firebase_core: ^1.24.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  flutter_spinkit: ^5.1.0
  google_fonts: ^3.0.1
  intl: ^0.17.0

dev_dependencies:
  bloc_test: ^9.1.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.2

flutter:
  uses-material-design: true
  generate: true
  assets:
  - Assets/Images/

